name: Static Analysis Scan


on:
  push:
    branches: [main, deploy]
  pull_request:
    branches: [main, dev]
jobs:
  Scan-Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Perform Scan
      uses: AppThreat/sast-scan-action@master
      with:
        type: "nodejs"
    - name: Upload Report
      uses: actions/upload-artifact@v1
      with:
        name: Reports
        path: Reports
