# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - preppal-be

on:
  push:
    branches: [ "dev", "hwbit/deploy-to-azure" ] #TODO: change this to main later
  workflow_dispatch:

env:
  AZURE_KEY: ${{ secrets.AZURE_KEY }}
  AZURE_CONNECTION_KEY: ${{ secrets.AZURE_CONNECTION_KEY }}
  MONGO_URI: ${{ secrets.MONGO_URI }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./preppal-be

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
        
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: preppal-be/node-app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
          path: preppal-be/node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D2E8A10972E54338AA34EE7FE5A33E9F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1924AA7609B6431D97D7F8790E7C06D3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_053489C159F645159E873CE96D47566E }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'preppal-be'
          slot-name: 'Production'
          package: .
          