name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Configure GitHub token for deployment
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm config set //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN

    - name: Set Author
      run: |
        git config --global user.email "cuetarai@myumanitoba.ca"
        git config --global user.name "Izan"

    - name: Build & Deploy
      working-directory: ./preppal-fe
      run: |
        npm install
        npm run deploy
