name: Release to Docker Hub

on:
  push:
    branches: [ "dev", "hwbit/docker-deploy"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: preppal-fe
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/preppal-fe:latest
          build-args: |
            MONGO_URI=${{ secrets.MONGO_URI }}
            ORIGIN=http://localhost:3000

      - name: Build and push client image
        uses: docker/build-push-action@v5
        with:
          context: preppal-be
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/preppal-be:latestt
          build-args: BACKEND_BASE_URL=http://localhost:9001