name: Github Pages Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Configure GitHub token for deployment
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm config set //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN

    - name: Set Author
      run: |
        git config --global user.email "cuetarai@myumanitoba.ca"
        git config --global user.name "Izan"

    - name: Build & Deploy
      working-directory: ./preppal-fe
      run: |
        npm ci
        npm run deploy
